### ISSUE TITLE
Add support for inline source maps

### ISSUE THREAD

**Issue by myst729** [microsoft/vscode-ios-web-debug#13]
I'm trying to get this work with my Mac and iPhone.

I read [this page](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-ios-web) very carefully, and installed the prerequisites like brew package, but did not work.

I got this all the time:
> Error [debugger-for-chrome] Got a response from the target app, but no target pages found

My Mac and iPhone are in the same WiFi network. The project is served from my Mac with a node dev server. I'm visiting the dev page on iPhone via URL like `http://192.168.7.100:8080/`. iPhone is plugged to Mac with the USB cable, and set to **trust**.

Here are my launch.json configs, none of these works:
```json
    {
      "name": "Launch iOS Safari",
      "type": "ios",
      "request": "launch",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "port": 9222,
      "deviceName": "*",
      "url": "http://192.168.7.100:8080/*"
    },
    {
      "name": "Launch iOS Safari via Tunnel",
      "type": "ios",
      "request": "launch",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "port": 9222,
      "deviceName": "*",
      "tunnelPort": 8080
    },
    {
      "name": "Attach iOS Safari",
      "type": "ios",
      "request": "attach",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "port": 9222,
      "deviceName": "*",
      "url": "http://192.168.7.100:8080/*"
    }
```

I'm using **Debugger for Chrome** for macOS Chrome too, and it works perfectly. So I'm stuck here, cannot figure out what I was missing.

My environment and device:
- Macbook Pro: macOS 10.12.1, VS Code 1.7.1, Debugger for iOS Web 0.1.2.
- iPhone 6: iOS 10.1 (no iOS Chrome installed).

**Comment by myst729** [comment]
Tried to set up on a Windows 7 laptop. Works fine with PC Chrome, same error info for iPhone Safari.

**Comment by auchenberg** [comment]
Hi @myst729 

1) Do you have Safari open on your ios device with the tab open?
2) Can you try to start the debugger and and go to `http://localhostl:9222/json` and dump the output here?

Let's get this working for you :)

**Comment by myst729** [comment]
@auchenberg 

1. I tried either with or without an open tab on `http://192.168.7.100:8080`, none of the three configs works.
2. On `http://192.168.7.100:9222` it says

    > iOS Devices:

**Comment by auchenberg** [comment]
Hi @myst729 

Thanks! Given your are MacOS, can you try the following;
1. Open a terminal
2. Run `ios_webkit_debug_proxy` in your terminal. 
3. Connect your iPhone over USB, start safari with a tab open on `google.com`
4. Make sure the `Web Inspector` option is enabled on your iOS device

**Action:**
1. Go to `http://localhost:9221` and paste the output here
2. Go to `http://localhost:9222/json` and paste the output here

**Comment by myst729** [comment]
- Turned on iPhone Safari **Web Inspector** and connected it to laptop over USB.

- Visit https://github.com/ on iPhone Safari.

- Run `ios_webkit_debug_proxy` on Mac terminal, successfully connected to iPhone.
   <img width="461" alt="qq20161113-0 2x" src="https://cloud.githubusercontent.com/assets/519733/20245255/5411fdf0-a9d8-11e6-942d-03f4f96b388c.png">

- Visit http://localhost:9221 on Mac Chrome, iPhone is listed there too:
   ```
   iOS Devices:
   localhost:9223 - Leo’s iPhone
   ```

- Visit http://localhost:9222/json on Mac Chrome, nothing:
   ```
   []
   ```

**Comment by myst729** [comment]
If I modify the config as following - change `port` to `2223`:
```
    {
      "name": "Attach iOS Safari",
      "type": "ios",
      "request": "attach",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "port": 9223,
      "deviceName": "*",
      "url": "http://192.168.7.100:8080"
    }
```

I get this:
> [debugger-for-chrome] Can't find a target that matches: http://192.168.7.100:8080. Available pages: ["http://192.168.7.100:8080/#/home"]

My app is an SPA with client routing. This is slightly different from debugging laptop Chrome. Chrome debugger can match it.

I went on modifying the config, change `url` to `http://192.168.7.100:8080/*`, which I thought would match anyway:
```
    {
      "name": "Attach iOS Safari",
      "type": "ios",
      "request": "attach",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "port": 9223,
      "deviceName": "*",
      "url": "http://192.168.7.100:8080/*"
    }
```

This time the debugger runs, and VSC debug console is outputting messages. Looks great. But, break points are still not working. Says **Unverified Breakpoint**, and could not stop at all.
<img width="256" alt="qq20161115-0 2x" src="https://cloud.githubusercontent.com/assets/519733/20245445/d058def2-a9dc-11e6-9e97-a4221e3a1627.png">

Also, since I'm using stylus to write styles together with webpack-stylus-loader, in debug console there are lots of such messages, which does not happen when debugger laptop Chrome:
```
Unexpected CSS token: :
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Unexpected CSS token: :
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
Invalid CSS property declaration at: *
```

**Comment by auchenberg** [comment]
@myst729 Okay, now we got VS Code connected to your iOS device. I think the next issue is a `webRoot` source map issue. Can you set `diagnosticLogging` to `true`in the config, and copy+paste the log in here, after you tried to set a breakpoint?

**Comment by myst729** [comment]
This time iPhone connects to port `9222`, weird.

Visit `http://localhost:9221/json` on Mac Chrome:
```
[{
   "deviceId": "****************************************", // some SHA-1 string I guess
   "deviceName": "Leo’s iPhone",
   "url": "localhost:9222"
}]
```

Visit `http://localhost:9222/json` on Mac Chrome:
```
[{
   "devtoolsFrontendUrl": "",
   "faviconUrl": "",
   "thumbnailUrl": "/thumb/http://192.168.7.100:8080/#/blog/guide/2016/vuelog-hackers-guide",
   "title": "Vuelog Dev | [TODO] Vuelog hacker’s guide",
   "url": "http://192.168.7.100:8080/#/blog/guide/2016/vuelog-hackers-guide",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/1",
   "appId": "PID:2734"
}]
```

The url `http://192.168.7.100:8080/#/blog/guide/2016/vuelog-hackers-guide` is exactly what I'm visiting on iOS Safari.

For now I think we can be pretty sure that the debug proxy is running just fine.

In VSC console there are lots similar info like this:
```
  ›OS: darwin x64
  ›Node: v6.5.0
  ›vscode-chrome-debug-core: 0.1.16
  ›debugger-for-ios-web: 0.1.2
  ›spawn('/usr/local/bin/ios_webkit_debug_proxy', ["--no-frontend","--config=null:9222,:9223-9323"])
  ›Discovering targets via http://127.0.0.1:9222/json
  ›SourceMaps.getMapForGeneratedPath: Finding SourceMap for debugadapter://1529 by URI: data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9+L2hpZ2hsaWdodC5qcy9saWIvbGFuZ3VhZ2VzL25peC5qcz8xYzM2Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLGdCQUFnQjtBQUNoQixXQUFXO0FBQ1g7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxPQUFPLHVCQUF1QjtBQUM5QixPQUFPO0FBQ1A7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EiLCJmaWxlIjoiMjYzLmpzIiwic291cmNlc0NvbnRlbnQiOlsibW9kdWxlLmV4cG9ydHMgPSBmdW5jdGlvbihobGpzKSB7XG4gIHZhciBOSVhfS0VZV09SRFMgPSB7XG4gICAga2V5d29yZDpcbiAgICAgICdyZWMgd2l0aCBsZXQgaW4gaW5oZXJpdCBhc3NlcnQgaWYgZWxzZSB0aGVuJyxcbiAgICBsaXRlcmFsOlxuICAgICAgJ3RydWUgZmFsc2Ugb3IgYW5kIG51bGwnLFxuICAgIGJ1aWx0X2luOlxuICAgICAgJ2ltcG9ydCBhYm9ydCBiYXNlTmFtZU9mIGRpck9mIGlzTnVsbCBidWlsdGlucyBtYXAgcmVtb3ZlQXR0cnMgdGhyb3cgJyArXG4gICAgICAndG9TdHJpbmcgZGVyaXZhdGlvbidcbiAgfTtcbiAgdmFyIEFOVElRVU9URSA9IHtcbiAgICBjbGFzc05hbWU6ICdzdWJzdCcsXG4gICAgYmVnaW46IC9cXCRcXHsvLFxuICAgIGVuZDogL30vLFxuICAgIGtleXdvcmRzOiBOSVhfS0VZV09SRFNcbiAgfTtcbiAgdmFyIEFUVFJTID0ge1xuICAgIGJlZ2luOiAvW2EtekEtWjAtOS1fXSsoXFxzKj0pLywgcmV0dXJuQmVnaW46IHRydWUsXG4gICAgcmVsZXZhbmNlOiAwLFxuICAgIGNvbnRhaW5zOiBbXG4gICAgICB7XG4gICAgICAgIGNsYXNzTmFtZTogJ2F0dHInLFxuICAgICAgICBiZWdpbjogL1xcUysvXG4gICAgICB9XG4gICAgXVxuICB9O1xuICB2YXIg[...]
  ›SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in debugadapter://1529
  ›SourceMap: creating for debugadapter://1529
  ›SourceMap: sourceRoot: 
  ›SourceMap: sources: ["webpack:///./~/highlight.js/lib/languages/nix.js?1c36"]
  ›Warning: SourceMap sources are inlined. This extension ignores inlined sources. If the paths are not correct, sourcemap support won't work.
  ›SourceMap: webRoot: /Users/Leo/Documents/Development/vuelog
  ›SourceMaps.getMapForGeneratedPath: exception while processing sourcemap: TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.getComputedSourceRoot (/Users/Leo/.vscode/extensions/msjsdiag.debugger-for-ios-web-0.1.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapUtils.js:50:38)
    at new SourceMap (/Users/Leo/.vscode/extensions/msjsdiag.debugger-for-ios-web-0.1.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:32:49)
    at /Users/Leo/.vscode/extensions/msjsdiag.debugger-for-ios-web-0.1.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapFactory.js:33:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

  ›SourceMap: creating for debugadapter://1831
  ›SourceMap: sourceRoot: 
  ›SourceMap: sources: ["webpack:///./src/components/VuelogPagination.vue?ed96"]
  ›Warning: SourceMap sources are inlined. This extension ignores inlined sources. If the paths are not correct, sourcemap support won't work.
  ›SourceMap: webRoot: /Users/Leo/Documents/Development/vuelog
  ›SourceMaps.getMapForGeneratedPath: exception while processing sourcemap: TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.getComputedSourceRoot (/Users/Leo/.vscode/extensions/msjsdiag.debugger-for-ios-web-0.1.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapUtils.js:50:38)
    at new SourceMap (/Users/Leo/.vscode/extensions/msjsdiag.debugger-for-ios-web-0.1.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:32:49)
    at /Users/Leo/.vscode/extensions/msjsdiag.debugger-for-ios-web-0.1.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapFactory.js:33:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

  Failed to load resource: The network connection was lost. (http://192.168.7.100:8080/__webpack_hmr)
  ›SourceMaps.setBP: /Users/Leo/Documents/Development/vuelog/src/helpers/index.js can't be resolved to a loaded script. It may just not be loaded yet.
```

I noticed it says:
```
  ›SourceMap: sources: ["webpack:///./src/components/VuelogPagination.vue?ed96"]
  ›Warning: SourceMap sources are inlined. This extension ignores inlined sources. If the paths are not correct, sourcemap support won't work.
  ›SourceMap: webRoot: /Users/Leo/Documents/Development/vuelog
  ›SourceMaps.getMapForGeneratedPath: exception while processing sourcemap: TypeError: Path must be a string. Received null
```

I used [vue-cli](https://github.com/vuejs/vue-cli) to setup a Vue.js repository. And in development it's running with sourcemaps inlined. Does that mean this extension currently cannot deal with my scenario?

**Comment by auchenberg** [comment]
Aha @myst729. The current version doesn't support inlined-sourcemaps, but we just landed that in https://github.com/Microsoft/vscode-chrome-debug-core, which this debugger is using. That's probably the reason for why it's working when you are using our Chrome debugger.

Stay tuned. I hope to make a new release next week.

**Comment by myst729** [comment]
Yep, I saw the debugger for Chrome updated quite often recently. Looking forward to a major update for iOS 😋

**Comment by myst729** [comment]
By the way, the `url` match is annoying too.

For macOS Chrome, `"url": "http://192.168.7.100:8080"` matches all pages under that domain. But this doesn't work for iOS now.

So I have to use `"url": "http://192.168.7.100:8080/*"`. And that brings another weird thing. Whenever routing occurs in my SPA, the url in iOS Safari changes to something like `http://192.168.7.100:8080/*#/some-route`, which should be `http://192.168.7.100:8080/#/some-route` (without the extra asterisk).
